[package]
name = "kgames"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[profile.release]
lto = true
strip = true
debug = false
codegen-units = 1
opt-level = "z" # "s"

[dependencies]
macroquad = {version = "0.4.8", features = ["audio"]}
[build-dependencies]
static_vcruntime = "2.0.0"