[package]
name = "kgames"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = true
strip = true
debug = false
incremental = false
codegen-units = 1
opt-level = "z" # "s"
panic = "abort"

[dependencies]
macroquad = {version = "0.4.8", features = ["audio"]}
rhai = "1.19.0"

[build-dependencies]
static_vcruntime = "2.0.0"
