[package]
name = "game_core"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = {version = "0.4.13", features = ["audio"]}

[dependencies.futures]
version = "0.3.30"
default-features = false
features = ["executor"]
